### ISSUE TITLE
PodTemplateSpec Does not allow configuring existing containers

### ISSUE THREAD

**Issue by kri5** [datastax/cass-operator#108]
I would have supposed that the containers and initcontainers already used by the operator could be configured/overriden by specifying some keys on the PodTemplateSpec, and thoses would be merge on top of the default values.

Use case would be to pass to the cassandra config init container some environment values interpolated from secrets, or some volumemounts, but it seems that it just append the keys to the others, so i end up with configuration with multiple "server-config-init" init containers or multiple "cassandra" containers.

Is this the expected behavior?

**Comment by bradfordcp** [comment]
Related #101 

**Short Answer:** Yes

**Long Answer:**

A collection of `initContainers` is by design. We prepend our `initContainer` to render out the basic configuration which then allows the user provided `PodTemplateSpec.initContainers` to modify any values that have been generated.

I don't expect to see many `cassandra` containers in the same Pod. Do you have a use case for this?  Right now, we are _currently_ of the mindset that changes to the `cassandra` container should be handled with fields at the top-level of the `CassandraDatacenter` CR. 

It appears as though you expect that if you provide an entry in `PodTemplateSpec.containers` with the same `name` that any values applied to that container would be merged with the container spec prepared by the operator. Is that accurate?

What changes are you considering making to the `cassandra` container?

**Comment by kri5** [comment]
Below comes an example of what i am trying to achieve

```
    podTemplateSpec:                                                                                                
      spec:                                                                                                         
        volumes:                                                                                                    
          - name: truststore                                                                                        
            secret:                                                                                                 
              secretName: cassandra-tls                                                                         
        initContainers:                                                                                             
          - name: server-config-init                                                                                
            env:                                                                                                    
              - name: TRUSTSTORE_PASSWORD                                                                           
                valueFrom:                                                                                          
                  secretKeyRef:                                                                                     
                    name: cassandra-truststore-key                                                              
                    key: key                                                                                        
              - name: KEYSTORE_PASSWORD                                                                             
                valueFrom:                                                                                          
                  secretKeyRef:                                                                                     
                    name: cassandra-keystore-key                                                              
                    key: key                                                                                        
        containers:                                                                                                 
          - name: cassandra                                                                                         
            volumeMounts:                                                                                           
              - mountPath: /secrets/tls                                                                             
                name: truststore                                                                                    
                                                                                                                    
        tolerations:                                                                                                
          - key: dedicated                                                                                          
            operator: Equal                                                                                         
            value: cassandra                                                                                        
            effect: NoSchedule
...
  config:                                                                                                         
      cassandra-yaml:                                                                                                                                         
        server_encryption_options:
          keystore: /secrets/tls/keystore.jks
          keystore_password: $KEYSTORE_PASSWORD                                                                     
          truststore: /secrets/tls/truststore.jks                                                                   
          truststore_password: $TRUSTSTORE_PASSWORD 
```

What i want to achieve it being able to pass values from secrets via env to the init-container dealing with the configuration, and mounting volumes into the cassandra container, and also specifing tolerations on all thoses containers.
