### ISSUE TITLE
Add support for Reaper

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#113]
I propose adding support for running repairs with [Reaper](http://cassandra-reaper.io) by introducing a Reaper sidecar. Reaper already has a [sidecar mode](http://cassandra-reaper.io/docs/usage/sidecar_mode/) which lends itself really well to this. 

High level goals for initial integration include:

* Run Reaper as a sidecar container
* Make deploying Reaper optional
* Provide ability to add/remove Reaper after `CassandraDatacenter` has already been created
* Make Reaper UI accessible through a service
    * Reaper users rely heavily on using the UI for managing repairs
* Expose minimal Reaper configs through `CassandraDatacenter` CRD
* Enable Reaper authentication by default and provide (Reaper) admin credentials in none specified

An example manifest might look like this:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.6"
  managementApiAuth:
    insecure: {}
  size: 3
  racks:
    - name: rack1
    - name: rack2
    - name: rack3
  reaper:
    enabled: true
    adminUserSecretName: reaperAdmin
```

When Reaper is enabled this would result in the following:

* Deploy Reaper sidecar container in Cassandra pod
* Initialize `reaper_db` keyspace
* Add Cassandra cluster to Reaper (done automatically when using Reaper sidecar mode)
* Expose Reaper UI via service

What is not in scope for this ticket?

* Exposing any and all Reaper configuration
    * We want to expose as little configuration as possible and provide sensible defaults
* Running Reaper in a mode other than sidecar
    * This would be better suited for stand alone Reaper operator I am working on, [reaper-operator](https://github.com/thelastpickle/reaper-operator)
