### ISSUE TITLE
Is there a way to set annotations on the created pods?

### ISSUE THREAD

**Issue by rltvty** [datastax/cass-operator#154]
It would be great if there was a way to pass a list of annotations (and maybe labels too), that would be applied to all the StatefulSets and resultant Pods created by the Datacenter config.

My specific use case is for adding annotations for the configuration of Linkerd service mesh on the pods.  I'm currently setting config at the namespace level, but I'd much rather set it at the pod level.

Ref: https://linkerd.io/2/reference/proxy-configuration/

**Comment by jimdickinson** [comment]
Sorry for the delay - this got lost in the shuffle around the 4th of July. Yes cass-operator supports this!

Here's an example of how to do it with the top level `podTemplateSpec` field in the `CassandraDatacenter`.

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cass-operator
spec:
  clusterName: cluster2
...
  podTemplateSpec:
    metadata:
      annotations:
        last-edited-by: Jim
      labels:
        cass-env: dev
...
```

when the pods are (re)created, they'll have those custom labels and annotations...

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    last-edited-by: Jim
  creationTimestamp: "2020-07-15T02:00:27Z"
  generateName: cluster2-dc1-rack1-sts-
  labels:
    app.kubernetes.io/managed-by: cass-operator
    cass-env: dev
    cassandra.datastax.com/cluster: cluster2
    cassandra.datastax.com/datacenter: dc1
    cassandra.datastax.com/node-state: Started
    cassandra.datastax.com/rack: rack1
    cassandra.datastax.com/seed-node: "true"
    controller-revision-hash: cluster2-dc1-rack1-sts-6f8f8bb9ff
    statefulset.kubernetes.io/pod-name: cluster2-dc1-rack1-sts-0
...
```
