### ISSUE TITLE
JMX port exposing 

### ISSUE THREAD

**Issue by SkySonR** [datastax/cass-operator#163]
Hi! There are no information how to expose JMX port. I have added necessary options to java arguments: 
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.rmi.port=7199
In the code I see the commend and nothing else:
https://github.com/datastax/cass-operator/blob/4dd8e7c5d53398bb827dda326762c2fa15c131f9/operator/pkg/apis/cassandra/v1beta1/cassandradatacenter_types.go#L557

So I think users should have ability to export any ports they want to pod and into service also.

**Comment by jimdickinson** [comment]
What do you want to expose JMX to? All pods in k8s will have access by default. In general we want to deemphasize using JMX in favor of using the Management API REST interface.

**Comment by SkySonR** [comment]
@jimdickinson Hi! Thank you for active development and support! I need both, exposing to cluster and outside. I got it, will try kubectl expose. But I am not sure that it will works because of JMX port does not defended in pod configuration and there are no way to do it. From dse pod created by operator:
```
    name: cassandra
    ports:
    - containerPort: 9042
      name: native
      protocol: TCP
    - containerPort: 8609
      name: inter-node-msg
      protocol: TCP
    - containerPort: 7000
      name: intra-node
      protocol: TCP
    - containerPort: 7001
      name: tls-intra-node
      protocol: TCP
    - containerPort: 8080
      name: mgmt-api-http
      protocol: TCP
```
