### ISSUE TITLE
Startup checks, vm.max_map_count

### ISSUE THREAD

**Issue by dmsolow** [datastax/cass-operator#187]
On startup I see the following warnings:
```
WARN  [main] 2020-08-08 15:40:04,254 NativeLibrary.java:189 - Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
WARN  [main] 2020-08-08 15:40:04,299 StartupChecks.java:311 - Maximum number of memory map areas per process (vm.max_map_count) 65530 is too low, recommended value: 1048575, you can change it with sysctl.
```

Are there plans to resolve these issues by default using the operator? If not, do you have any guidance on resolving them?

For reference, the Elasticsearch helm chart that I'm running has the following initContainer:
```
initContainers:
  - command:
    - sysctl
    - -w
    - vm.max_map_count=262144
    image: ...
    imagePullPolicy: IfNotPresent
    name: configure-sysctl
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
```

How can I add such an initContainer to my cassdc?

**Comment by jimdickinson** [comment]
I'm not sure if the first warning is an issue - it's not possible to enable swap with Kubernetes, see https://github.com/kubernetes/kubernetes/issues/53533

If you want to try to address the max_map_count, that approach should work with Cass Operator. We've got an integration test like this here -> https://github.com/datastax/cass-operator/blob/86b32ee3fc21e8cd33707890ff580a15db5d691b/tests/testdata/default-single-rack-single-node-extra-container-dc.yaml#L24

You'll want something like

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: mydc
spec:
  clusterName: mycluster
...
  size: 1
...
  racks:
    - name: r1
  podTemplateSpec:
    spec:
      initContainers:
        - command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          image: ...
          imagePullPolicy: IfNotPresent
          name: configure-sysctl
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
...
```

Let us know how that works for you - we can add this example to the docs if it's helpful.

**Comment by shivpathak** [comment]
@jimdickinson I also looking solution for the same mentioned issue (raising vm.max_map_count) params.

I tried following manifest:

```
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: glowroot
  namespace: capabilities
spec:
  clusterName: cassandra
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  racks:
  - name: rack1
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: gp2
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 300Gi
  podTemplateSpec:
    spec:
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=1048575
        image: linuxkit/sysctl:v0.8
        imagePullPolicy: IfNotPresent
        name: configure-sysctl
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 2G
      max_heap_size: 2G
```

**But when I apply I get following error:**

The CassandraDatacenter "glowroot" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"cassandra.datastax.com/v1beta1", "kind":"CassandraDatacenter", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cassandra.datastax.com/v1beta1\",\"kind\":\"CassandraDatacenter\",\"metadata\":{\"annotations\":{},\"name\":\"glowroot\",\"namespace\":\"capabilities\"},\"spec\":{\"clusterName\":\"cassandra\",\"config\":{\"cassandra-yaml\":{\"authenticator\":\"org.apache.cassandra.auth.PasswordAuthenticator\",\"authorizer\":\"org.apache.cassandra.auth.CassandraAuthorizer\",\"role_manager\":\"org.apache.cassandra.auth.CassandraRoleManager\"},\"jvm-options\":{\"initial_heap_size\":\"2G\",\"max_heap_size\":\"2G\"}},\"managementApiAuth\":{\"insecure\":{}},\"podTemplateSpec\":{\"spec\":{\"initContainers\":[{\"command\":[\"sysctl\",\"-w\",\"vm.max_map_count=1048575\"],\"image\":\"linuxkit/sysctl:v0.8\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"configure-sysctl\",\"resources\":{},\"securityContext\":{\"privileged\":true,\"runAsUser\":0}}]}},\"racks\":[{\"name\":\"rack1\"}],\"resources\":{\"limits\":{\"cpu\":1,\"memory\":\"4Gi\"},\"requests\":{\"cpu\":1,\"memory\":\"4Gi\"}},\"serverType\":\"cassandra\",\"serverVersion\":\"3.11.6\",\"size\":1,\"storageConfig\":{\"cassandraDataVolumeClaimSpec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"300Gi\"}},\"storageClassName\":\"gp2\"}}}}\n"}, "creationTimestamp":"2020-08-10T11:19:50Z", "generation":1, "name":"glowroot", "namespace":"capabilities", "uid":"e6e54154-8fb9-4284-9dfa-ddd9a20fa63c"}, "spec":map[string]interface {}{"clusterName":"cassandra", "config":map[string]interface {}{"cassandra-yaml":map[string]interface {}{"authenticator":"org.apache.cassandra.auth.PasswordAuthenticator", "authorizer":"org.apache.cassandra.auth.CassandraAuthorizer", "role_manager":"org.apache.cassandra.auth.CassandraRoleManager"}, "jvm-options":map[string]interface {}{"initial_heap_size":"2G", "max_heap_size":"2G"}}, "managementApiAuth":map[string]interface {}{"insecure":map[string]interface {}{}}, "podTemplateSpec":map[string]interface {}{"spec":map[string]interface {}{"initContainers":[]interface {}{map[string]interface {}{"command":[]interface {}{"sysctl", "-w", "vm.max_map_count=1048575"}, "image":"linuxkit/sysctl:v0.8", "imagePullPolicy":"IfNotPresent", "name":"configure-sysctl", "resources":map[string]interface {}{}, "securityContext":map[string]interface {}{"privileged":true, "runAsUser":0}}}}}, "racks":[]interface {}{map[string]interface {}{"name":"rack1"}}, "resources":map[string]interface {}{"limits":map[string]interface {}{"cpu":1, "memory":"4Gi"}, "requests":map[string]interface {}{"cpu":1, "memory":"4Gi"}}, "serverType":"cassandra", "serverVersion":"3.11.6", "size":1, "storageConfig":map[string]interface {}{"cassandraDataVolumeClaimSpec":map[string]interface {}{"accessModes":[]interface {}{"ReadWriteOnce"}, "resources":map[string]interface {}{"requests":map[string]interface {}{"storage":"300Gi"}}, "storageClassName":"gp2"}}}}: validation failure list:

**I am using cassandra-operator version:** `datastax/cass-operator:1.3.0`

**Comment by dmsolow** [comment]
@shivpathak it worked for me when I added `containers: []`. Here's my full `podTemplateSpec`:
```
  podTemplateSpec:
    spec:
      initContainers:
        - command:
          - sysctl
          - -w
          - vm.max_map_count=1048575
          image: busybox
          imagePullPolicy: IfNotPresent
          name: configure-sysctl
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
      containers: []
```
