### ISSUE TITLE
Reaper does not work when Cassandra authentication is used

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#211]
Consider the following example `CassandraDatacenter` manifest:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.6"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  reaper:
    enabled: true
  config:    
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
```

Cass Operator will create a C* cluster with authentication enabled. Reaper talks to Cassandra using both JMX and CQL. The CQL calls will fail because no credentials are passed to Reaper.

It might be good for `.spec.reaper` to allow you to specify a C* user/role for Reaper to use. I think it is sufficient for now though for the operator to auto generate a role for Reaper.
