### ISSUE TITLE
additionalSeeds doesn't support domains

### ISSUE THREAD

**Issue by aryklein** [datastax/cass-operator#232]
I'm trying to use a list of domains in `additionalSeeds`, like this:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cassandra-k8s
  serverType: cassandra
  serverVersion: "3.11.6"
  managementApiAuth:
    insecure: {}
  additionalSeeds:
   - seed-cassandra-k8s.query.consul
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: cass-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
```

But get this error:

```
subsets[0].addresses[0].ip: Invalid value: "seed-cassandra-k8s.query.consul": must be a valid IP address]
```
Is there any way to support domains instead of IPs? 
Pods IPs are ephemeral.
