### ISSUE TITLE
Add tolerations

### ISSUE THREAD

**Issue by nbenaglia** [datastax/cass-operator#239]
`nodeSelector` works, but if pod hasn't tolerations, it cannot be scheduled on a tainted node. 

See [Taints and Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for concepts.

CassandraDatacenter should accept a toleration definition.

**Comment by jimdickinson** [comment]
Does using `podTemplateSpec` not work for tolerations? I think it was actually the original request that got us working on generically accepting podSpec features that we did not make explicit parts of our CRD.

**Comment by nbenaglia** [comment]
It does not work:

`CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: spec.podTemplateSpec.spec.containers: Required value`

This is caused here: https://github.com/datastax/cass-operator/blob/711187864f32cfed1feaa8c981c268299e6f3137/operator/pkg/apis/cassandra/v1beta1/cassandradatacenter_types.go#L249

where `*corev1.PodTemplateSpec` has Containers []Container with comment:
`There must be at least one container in a Pod.`

This problem is linked to issue: #234

**Comment by jimdickinson** [comment]
Yes - can you set containers to an empty array like this?

```yaml
  podTemplateSpec:
    metadata:
      labels:
        customlabel: "123"
    spec:
      containers: []
```

**Comment by nbenaglia** [comment]
Ok, the empty array worked. Thanks.

In this snippet all works, but affinity is not added to the rack one (created by the operator):

```
    podTemplateSpec:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - "cassandra"
        containers: []
        nodeSelector:
          role: cassandra
        tolerations:
        - key: "cassandra"
          operator: "Exists"
          effect: "NoSchedule"
```
