### ISSUE TITLE
Support for NodeSelector and Node Taints in cassandra cluster ?

### ISSUE THREAD

**Issue by mizunos** [datastax/cass-operator#254]
My use of Cassandra is not within a K8s cluster of of its own.  It is in its own NodePool within a GKE cluster.  Able to add toleration to the cass-operator deployment (in the manifest.yaml) but is not able to control the deployment of Cassandra dc to a set of nodes in a Nodepool dedicated to Cassandra.  Try adding toleration definition to cassandra dc yaml file but did not work.
Operator works by adding toleration in `cass-operator` manifest.yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cass-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cass-operator
  template:
    metadata:
      labels:
        name: cass-operator
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "cassandra"
        effect: "NoSchedule"
      nodeSelector:
        dedicated: cassandra
```

Adding the following to cassdc-example.yaml did not work

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:

  # The datacenter name.
  name: dc1

spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cortex"
      effect: "NoSchedule"
  #nodeSelector:
  #  dedicated: cassandra
  # The cluster name.
  clusterName: cluster1

  # The number of server nodes.
  size: 3

  # The rack definitions.
  racks:
    - name: rack1
    - name: rack2
    - name: rack3
```
