### ISSUE TITLE
Allow for specifying additional labels on client service

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#293]
In EKS, when stateful sets have an external DNS annotation applied (`external-dns.alpha.kubernetes.io/hostname`) the underlying pods become available at an external DNS address.

In GKE, this same tactic results in, nothing. Instead, the annotation must be applied to the service (ideally the client service) for the same behavior to be exhibited.

The CassandraDatacenter spec should allow for specifying labels on the services it creates

**Comment by jsanda** [comment]
I will work on a PR for this.

**Comment by jeromatron** [comment]
Would the CassandraDatacenter spec allow for specifying annotations as well?

**Comment by jsanda** [comment]
>Would the CassandraDatacenter spec allow for specifying annotations as well?

That seems reasonable to me. I can add support for that as well.

@jeromatron do you want to specify label/annotations for only the client service or for all of the headless services that cass-operator creates? If we are adding the ability to set labels/annotations for one service, I wonder does it makes to go ahead and support for all of them.

**Comment by jtyl2017** [comment]
sample annotations required in the metadata.annotations section of cluster headless service (e.g. cluster1-dc1-service created by cass-operator)
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    external-dns.alpha.kubernetes.io/hostname: <dns here>
    external-dns.alpha.kubernetes.io/ttl: "300"
```
