### ISSUE TITLE
Add ability to add sidecars

### ISSUE THREAD

**Issue by cscetbon** [datastax/cass-operator#294]
#263 says that it provides a way to configure existing init-containers/containers, but it doesn't say that you can add new containers. Please confirm I'm right and if that's the case then having the ability to add sidecars is needed for us, users of CassKop. You can find examples at https://orange-opensource.github.io/casskop/docs/3_configuration_deployment/5_sidecars but we use sidecars to configure loggers, specific probes etc... As you can see we use the type containers that way users can fill everything they need like env, images, volumes, commands etc..
It's also important to note that in order to provide those sidecars some context we pass them env variables like the rack, the dc etc...

**Comment by jsanda** [comment]
You can in fact add new containers. Here is an example from some work I was doing earlier today:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: multi-dc
  serverType: cassandra
  serverVersion: 3.11.7
  canaryUpgrade: true
  canaryUpgradeCount: 0
  managementApiAuth:
    insecure: {}
  size: 3
  allowMultipleNodesPerWorker: false
  racks:
  - name: us-east1-b
    zone: us-east1-b
  podTemplateSpec:
    spec:
      initContainers:
        - name: jmx-credentials
          image: jsanda/jmx-credentials
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /config
            name: server-config
      containers:
        - name: cassandra
          env:
            - name: LOCAL_JMX
              value: "no"
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi      
```
Note that I included the `cassandra` container which the operator creates. The operator will merge my changes which is really nice.

There is a downside with the `podTemplateSpec` property though. Let's say that you _only_ want to add an initContainer. You cannot do that because the pod spec requires that the `containers` property is non-empty. This can be confusing and for that reason I think we should support adding initContainers separately from the `podTemplateSpec` property.

**Comment by bradfordcp** [comment]
To be clear you _can_ specify `containers: []` and it will accept the pod template spec. WRT annotating added containers with additional environment variables do you have a list of keys / values? I'm certain that's something that can be added without too much issue.

**Comment by jsanda** [comment]
>To be clear you can specify containers: [] and it will accept the pod template spec

Actually, you _must_ specify containers which is what I do not like. Here is an example to illustrate:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: multi-dc-test
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  allowMultipleNodesPerWorker: false
  racks:
  - name: us-east1-b
    zone: us-east1-b
  podTemplateSpec:
    spec:
      initContainers:
        - name: jmx-credentials
          image: jsanda/jmx-credentials
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /config
            name: server-config
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

```
$ kubectl apply -f dc2-cassdc.yaml
The CassandraDatacenter "dc2" is invalid: spec.podTemplateSpec.spec.containers: Required value
```
In the case where you _only_ want to specify additional initContainers, it is confusing at best and error prone at worst that you have to specify app containers. As I mentioned in my previous comment, I believe this is because the `PodSpec` type does not allow an empty value for the `containers` field. Given this, I think cass-operator should allow you to specify initContainers separately similar to what CassKop does.
