### ISSUE TITLE
github actions CI does not support PRs from forks

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#30]
I came across this in #28.

The build for #28 failed with `Error: MO_ECR_REPO is a required environment variable`.

And the github actions [workflow](https://github.com/datastax/cass-operator/blob/master/.github/workflows/operatorPRBuildAndDeploy.yml#L28) has this:

```yaml
      - name: Deploy to ECR
        if: github.repository == 'datastax/cass-operator'
        env:
          MO_ECR_ID: ${{ secrets.ECR_ID }}
          MO_ECR_SECRET: ${{ secrets.ECR_SECRET }}
          MO_ECR_REPO: ${{ secrets.ECR_REPO }}
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          export MO_TAGS=$(cat ./build/tagsToPush.txt)
          mage operator:deployToECR
```
It looks like the necessary env vars only get set if the repo is `datastax/cass-operator`.
