### ISSUE TITLE
Unable to specify busybox version for server-system-logger

### ISSUE THREAD

**Issue by sigfridh** [datastax/cass-operator#300]
I didn't find a way to specify the busybox docker image version, also i try to override the spec like this:

````
   podTemplateSpec:
     spec:
       containers:
         - name: "server-system-loger"
           args: ["/bin/sh", "-c", "tail -n+1 -F /var/log/cassandra/system.log"]
           image: busybox:1.31.1
           resources:
             limits:
               cpu: 100m
               memory: 64M
             requests:
               cpu: 100m
               memory: 64M
           terminationMessagePath: "/dev/termination-log"
           terminationMessagePolicy: "File"
           imagePullPolicy: IfNotPresent
           volumeMounts:
             - mountPath: "/var/log/cassandra"
               name: "server-logs"
````
but it only append a new container in addition to the busybox:latest one
any ideas?
Thanks
Sigfrid
