### ISSUE TITLE
Investigate support for multiple validating webhook configurations

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#301]
Discussing webhooks with @jimdickinson on Thursday we discussed the case where multiple cass-operator instances are running within a single k8s cluster (namespace scoped). The ValidatingWebhook is cluster scoped just like CRDs. This presents a problem when multiple operators are installed. Which should respond to a validation request and who should be called?

Supposedly (Jim knows more on this topic than I do) ValidatingWebhooks support multiple configurations where they all get called in parallel. With this detail in mind, let's explore where each operator adds itself as a party who is interested in validating a CRD. If the generated CRD is within a WATCH_NAMESPACE for this instance of the operator, then validate it. If not, pass the CRD as it isn't our problem.

Ideally this ticket is a spike on research, with follow-up tickets for implementation if possible.

_Please excuse any mixed up terms above, I'm going off Slack archives and **very** light knowledge in this space_

**Comment by jsanda** [comment]
I was actually investigating this some yesterday for k8ssandra. I will do some more investigation and report back my findings.

**Comment by jsanda** [comment]
While a ValidatingWebhookConfiguration is cluster-scoped, it is entirely possible to effectively limit the scope of a webhook to a particular namespace using label selectors.

I have done some preliminary testing to verify that this is possible. Here is an example manifest:

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: cassandradatacenter-webhook-registration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: cassandradatacenter-webhook-service
      namespace: webhook-test
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: cassandradatacenter-webhook.cassandra.datastax.com
  namespaceSelector:
    matchExpressions:
      - key: validatingWebhook-enabled
        operator: In
        values: [ "true" ]
      - key: meta.helm.sh/release-name
        operator: In
        values : [ "webhook-test" ]
  rules:
  - apiGroups:
    - cassandra.datastax.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandradatacenters
    scope: 'Namespaced'
  sideEffects: None
  timeoutSeconds: 10
```

Note the `namespaceSelector` field. The namespace has to have those labels. I was researching this in the context of Helm, and I found that this is pretty common. 

I also want to point out the `scope: 'Namespaced'` property. That does not make the webhook namespace-scoped. It only limits the rule to match objects that are namespace-scoped. The webhook could still match CassandraDatacenters across multiple namespaces. This setting does not obviate the need for label selectors as discussed above.

I also found that Helm does not provide an easy way to apply labels to the namespace in which the chart is being installed. We need to use a chart hook to apply the labels.

As an aside I have talked with @jimdickinson about separating the webhook out into it own separate binary and deployment. I agree that we should do that; however, it is not necessary for what we are discussing here. I prefer to tackle that separately after submitting a PR for this.
