### ISSUE TITLE
Unable to create Datacenter on Openshift 4.6

### ISSUE THREAD

**Issue by mkuligow** [datastax/cass-operator#314]
Hi,
I have problem with Cassandra operator (1.14) on Openshift 4.6.3 (Kubernetes version 1.19). 

### Sumarry:
Got this during CassandraDatacenter creation
```
kubectl -n cass-operator logs cassdc/dc1
error: no kind "CassandraDatacenter" is registered for version "cassandra.datastax.com/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

### Installation process:
1. Apply [manifest](https://pastebin.pl/view/02160c68) with CRD/RBAC
2. Create storage for Cassandra
```
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-2
          - worker-0
          - worker-1
  storageClassDevices:
    - storageClassName: "localblock-sc"
      volumeMode: Block
      devicePaths:
        - /dev/sdb
```
3. Deploy datacenter
```
apiVersion: v1
kind: Namespace
metadata:
  name: cass-dc
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cass-operator
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: localblock-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
```

Now i got issue.

### Cluster spec:
*  3 workers and 3 masters
* Each machine has 32 GB RAM, 8 cores
* 200GB on each node
* 160GB as local storage volume on worker nodes
