### ISSUE TITLE
Permission errors in cassandra container

### ISSUE THREAD

**Issue by florissmit10** [datastax/cass-operator#355]
When I create a CassandraDatacenter the cassandra pods wont start, and they have the following error:
```
Starting Management API
/docker-entrypoint.sh: line 68: /opt/mcac-agent/config/metric-collector.yaml: Permission denied
```
Iam using the following configuration:

```
# Sized to work on 3 k8s workers nodes with 1 core / 4 GB RAM
# See neighboring example-cassdc-full.yaml for docs for each parameter
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
  namespace: glp-cassandra
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 2Gi
      cpu: 1000m
  dockerImageRunsAsCassandra: true
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:    
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=3"     
```
We are running this on an on premise rancher environment.
Anyone have any ideas on what causes this?
