### ISSUE TITLE
Creating a user with a non-existent secret causes a panic

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#364]
Create a CassandraDatacenter like this:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
  users:
  - secretName: does-not-exist
    superuser: true
```

The `validateCassandraUserSecrets` function in `secrets.go` does not check that the secret actually exists. This in turn causes a panic like this:

```
E0121 03:45:47.364093       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1190 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1570740, 0x25047f0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1570740, 0x25047f0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/datastax/cass-operator/operator/pkg/reconciliation.validateCassandraUserSecretContent(0xc0001ac800, 0x0, 0x0, 0x0, 0x1)
        /cass-operator/operator/pkg/reconciliation/secrets.go:231 +0x3a
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).validateCassandraUserSecrets(0xc0000c28c0, 0xc0006ebaf0, 0x0, 0x0)
        /cass-operator/operator/pkg/reconciliation/secrets.go:286 +0x1df
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).isValid(0xc0000c28c0, 0xc0001ac800, 0xc000319410, 0xc0001b6a10)
        /cass-operator/operator/pkg/reconciliation/handler.go:301 +0x9f
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconcileCassandraDatacenter).Reconcile(0xc0007368c0, 0xc000789f99, 0x7, 0xc0007895ec, 0x3, 0x0, 0x0, 0x0, 0x0)
        /cass-operator/operator/pkg/reconciliation/handler.go:245 +0x773
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001aaa80, 0x15cc3c0, 0xc0006b6900, 0xc000793600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001aaa80, 0xc000793700)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001aaa80)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00048b2f0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00048b2f0, 0x3b9aca00, 0x0, 0xc000453401, 0xc00059db60)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00048b2f0, 0x3b9aca00, 0xc00059db60)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x136f4ba]

goroutine 1190 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1570740, 0x25047f0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/datastax/cass-operator/operator/pkg/reconciliation.validateCassandraUserSecretContent(0xc0001ac800, 0x0, 0x0, 0x0, 0x1)
        /cass-operator/operator/pkg/reconciliation/secrets.go:231 +0x3a
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).validateCassandraUserSecrets(0xc0000c28c0, 0xc0006ebaf0, 0x0, 0x0)
        /cass-operator/operator/pkg/reconciliation/secrets.go:286 +0x1df
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).isValid(0xc0000c28c0, 0xc0001ac800, 0xc000319410, 0xc0001b6a10)
        /cass-operator/operator/pkg/reconciliation/handler.go:301 +0x9f
github.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconcileCassandraDatacenter).Reconcile(0xc0007368c0, 0xc000789f99, 0x7, 0xc0007895ec, 0x3, 0x0, 0x0, 0x0, 0x0)
        /cass-operator/operator/pkg/reconciliation/handler.go:245 +0x773
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001aaa80, 0x15cc3c0, 0xc0006b6900, 0xc000793600)
```
