### ISSUE TITLE
Update minimal DSE example to include config for metrics collection

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#372]
```yaml
    # Enable the DSE metrics collector, and stand up collectd for prometheus to scrape
    10-write-prom-conf:
      enabled: true
      port: 9103
      staleness-delta: 300
```

should be included in https://github.com/datastax/cass-operator/blob/master/operator/example-cassdc-yaml/dse-6.8.x/example-cassdc-minimal.yaml
