### ISSUE TITLE
Change in imagepolicy of Image:busbox from Always to IfNotPresent

### ISSUE THREAD

**Issue by Smita8081** [datastax/cass-operator#377]
When I create a Cassandra cluster using cass-operator, there is sidecar container created using image busbox, whose policy is set to Always. In order to deploy pods on worker nodes, there is a restriction to have internet connectivity on worker nodes in order to pull that image everytime from dockerhub.

Also on trying to modify container information deployed by cass-operator, there is an error mentioning 
**Changes done :**
```
spec:
  podTemplateSpec:
    containers:
    - name: server-system-logger
      imagePullPolicy: IfNotPresent
```
**Error message:** 
"  **Warning  FailedCreate      14s (x14 over 56s)  statefulset-controller  create Pod config-cassandra-dc-r1-sts-0 in StatefulSet config-cassandra-dc-r1-sts failed error: Pod "config-cassandra-dc-r1-sts-0" is invalid: spec.containers[2].name: Duplicate value: "server-system-logger"** "

**Comment by krisiasty** [comment]
You are missing additional "spec:" between "podTemplateSpec:" and "containers:". This is very common mistake.
The corresponding fragment should look like this:
```
  podTemplateSpec:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - name: server-system-logger
        image: busybox:1.32.1-uclibc
        imagePullPolicy: IfNotPresent
```

Regarding the issue - not only imagePullPolicy should be set to IfNotPresent, but also image should be specified with a correct tag, i.e. `image: busybox:1.32.1-uclibc`.

**Comment by Smita8081** [comment]
> You are missing additional "spec:" between "podTemplateSpec:" and "containers:". This is very common mistake.
> The corresponding fragment should look like this:
> 
> ```
>   podTemplateSpec:
>     metadata:
>       creationTimestamp: null
>     spec:
>       containers:
>       - name: server-system-logger
>         image: busybox:1.32.1-uclibc
>         imagePullPolicy: IfNotPresent
> ```
> 
> Regarding the issue - not only imagePullPolicy should be set to IfNotPresent, but also image should be specified with a correct tag, i.e. `image: busybox:1.32.1-uclibc`.

Sorry mistaken, I have had tried what u mentioned above and yet I was not able to modify server-systerm-logger container's configuration. Have you tried changing that using above code, you mentioned?

**Comment by krisiasty** [comment]
Yes, it worked for me.

Here is a fragment of `kubectl get pods -o yaml` after the change (I modified the policy and container image):
```
  - args:
    - /bin/sh
    - -c
    - tail -n+1 -F /var/log/cassandra/system.log
    image: busybox:1.32.1-uclibc
    imagePullPolicy: IfNotPresent
    name: server-system-logger
```

If it's not working for you please check logs of the pod running operator - you will probably find there error message saying the operator cannot parse cassandradatacenter object configuration.
