### ISSUE TITLE
The securityContext of the initContainer should be adjustable to avoid the necesity for creating a SCC when using images able to handle random UIDs

### ISSUE THREAD

**Issue by rwmoin** [datastax/cass-operator#380]
In our Openshift environment we may only use images from defined registries, preferably Red Hat managed ones. Thus we adjusted the Cassandra Operator to use images from registry.connect.redhat.com, which worked as intended. However the operator unnecessarily  still sets the securityContext of the initContainer in the statefulSet to run as UID: 999, requiering a SCC event though the Red Hat image is capable of running as any random user.
Why is there no option to edit the securityContext in the customResource?
Due to some SCC problems in our Openshift 4.6 environment, we simply set the securityContext in the statefulSet to {}, which works perfectly fine. Wouldn't it be best practice to avoid the creation of unnecessary SCCs?

our customResource we used for testing this behavior (based on the minimal dse example)
```
# See neighboring example-cassdc-full.yaml for docs for each parameter
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: dse-cluster
  serverType: dse
  serverVersion: "6.8.4"
  configBuilderImage: 'registry.connect.redhat.com/datastax/cass-config-builder:1.0.0-2'
  serverImage: 'registry.connect.redhat.com/datastax/dse-server:6.8.4-ubi7'
  serviceAccount: datastax-sa
  superuserSecretName: dse-superuser
  disableSystemLoggerSidecar: true
  managementApiAuth:
    insecure: {}
  ## not working to adjust initContainers, apparently only for main containers like 'cassandra'
  # podTemplateSpec:
  #   spec:
  #     initContainers:
  #     - name: server-config-init
  #       securityContext: {}
  size: 2
  resources:
    limits:
      cpu: '500m'
      memory: 5Gi
    requests:
      cpu: 200m
      memory: 2Gi
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
  config:
    jvm-server-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=2
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=2"
```

The statefulSet created by the operator including the securityContext adjustments (and the original UID 999 as comment)
```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  annotations:
    cassandra.datastax.com/resource-hash: 1cmfuR4j9hrpAScVCiesWzPYwdpbE15uF10IJ5FfyGE=
  name: dse-cluster-dc1-default-sts
  uid: 8ca2286c-53c8-4cb6-8b2d-6fb0382bc217
  creationTimestamp: '2021-02-12T13:34:54Z'
  generation: 4
  namespace: dev-middleware
  ownerReferences:
    - apiVersion: cassandra.datastax.com/v1beta1
      kind: CassandraDatacenter
      name: dc1
      uid: aca3ba44-6f19-4b4b-bc3d-8636e234b839
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/managed-by: cass-operator
    cassandra.datastax.com/cluster: dse-cluster
    cassandra.datastax.com/datacenter: dc1
    cassandra.datastax.com/rack: default
spec:
  replicas: 2
  selector:
    matchLabels:
      cassandra.datastax.com/cluster: dse-cluster
      cassandra.datastax.com/datacenter: dc1
      cassandra.datastax.com/rack: default
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: cass-operator
        cassandra.datastax.com/cluster: dse-cluster
        cassandra.datastax.com/datacenter: dc1
        cassandra.datastax.com/node-state: Ready-to-Start
        cassandra.datastax.com/rack: default
    spec:
      restartPolicy: Always
      initContainers:
        - name: server-config-init
          image: 'registry.connect.redhat.com/datastax/cass-config-builder:1.0.0-2'
          env:
            - name: CONFIG_FILE_DATA
              value: >-
                {"cassandra-yaml":{},"cluster-info":{"name":"dse-cluster","seeds":"dse-cluster-seed-service"},"datacenter-info":{"graph-enabled":0,"name":"dc1","solr-enabled":0,"spark-enabled":0},"jvm-server-options":{"additional-jvm-opts":["-Ddse.system_distributed_replication_dc_names=dc1","-Ddse.system_distributed_replication_per_dc=2"],"initial_heap_size":"800M","max_heap_size":"800M"}}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: USE_HOST_IP_FOR_BROADCAST
              value: 'false'
            - name: RACK_NAME
              value: default
            - name: PRODUCT_VERSION
              value: 6.8.4
            - name: PRODUCT_NAME
              value: dse
            - name: DSE_VERSION
              value: 6.8.4
          resources:
            limits:
              cpu: '1'
              memory: 256M
            requests:
              cpu: '1'
              memory: 256M
          volumeMounts:
            - name: server-config
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccountName: datastax-sa
      schedulerName: default-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: cassandra.datastax.com/cluster
                    operator: Exists
                  - key: cassandra.datastax.com/datacenter
                    operator: Exists
                  - key: cassandra.datastax.com/rack
                    operator: Exists
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 120

      ## set automatically from the operator
      # securityContext:
      #   runAsUser: 999
      #   runAsGroup: 999
      #   fsGroup: 999
      ## desired would be 
      securityContext: {}

      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 5Gi
            requests:
              cpu: 200m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /api/v0/probes/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - wget
                  - '--output-document'
                  - /dev/null
                  - '--no-check-certificate'
                  - '--post-data='''''
                  - 'http://localhost:8080/api/v0/ops/node/drain'
          name: cassandra
          livenessProbe:
            httpGet:
              path: /api/v0/probes/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DS_LICENSE
              value: accept
            - name: DSE_AUTO_CONF_OFF
              value: all
            - name: USE_MGMT_API
              value: 'true'
            - name: MGMT_API_EXPLICIT_START
              value: 'true'
            - name: DSE_MGMT_EXPLICIT_START
              value: 'true'
          ports:
            - name: native
              containerPort: 9042
              protocol: TCP
            - name: tls-native
              containerPort: 9142
              protocol: TCP
            - name: internode
              containerPort: 7000
              protocol: TCP
            - name: tls-internode
              containerPort: 7001
              protocol: TCP
            - name: jmx
              containerPort: 7199
              protocol: TCP
            - name: mgmt-api-http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9103
              protocol: TCP
            - name: thrift
              containerPort: 9160
              protocol: TCP
            - name: internode-msg
              containerPort: 8609
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: server-config
              mountPath: /config
            - name: server-logs
              mountPath: /var/log/cassandra
            - name: server-data
              mountPath: /var/lib/cassandra
            - name: encryption-cred-storage
              mountPath: /etc/encryption/
          terminationMessagePolicy: File
          image: 'registry.connect.redhat.com/datastax/dse-server:6.8.4-ubi7'
      serviceAccount: datastax-sa
      volumes:
        - name: server-config
          emptyDir: {}
        - name: server-logs
          emptyDir: {}
        - name: encryption-cred-storage
          secret:
            secretName: dc1-keystore
            defaultMode: 420
      dnsPolicy: ClusterFirst
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: server-data
        creationTimestamp: null
        labels:
          app.kubernetes.io/managed-by: cass-operator
          cassandra.datastax.com/cluster: dse-cluster
          cassandra.datastax.com/datacenter: dc1
          cassandra.datastax.com/rack: default
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: gp2
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: dse-cluster-dc1-service
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
status:
  observedGeneration: 4
  replicas: 2
  readyReplicas: 2
  currentReplicas: 2
  updatedReplicas: 2
  currentRevision: dse-cluster-dc1-default-sts-5df989d4d
  updateRevision: dse-cluster-dc1-default-sts-5df989d4d
  collisionCount: 0
```
