### ISSUE TITLE
Permission denied error on pod start

### ISSUE THREAD

**Issue by timcosta** [datastax/cass-operator#381]
Hey all! I'm getting some errors in a new installation of this chart on k8s 1.18 in GKE.
```bash
$ kc logs jaeger-jaeger-rack1-sts-0 -c cassandra
Starting Management API
/docker-entrypoint.sh: line 68: /opt/mcac-agent/config/metric-collector.yaml: Permission denied
```

I believe this is similar to #355 which was closed with no solution listed. I'm wondering if there is any update to this situation, and possibly a solution available. Happy to test things if necessary, thanks in advance!

**Comment by jimdickinson** [comment]
hi @timcosta - could you post your CassandraDatacenter yaml, please?

**Comment by timcosta** [comment]
```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: jaeger
spec:
  clusterName: jaeger
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  racks:
  - name: rack1
  - name: rack2
  - name: rack3
  podTemplateSpec:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - "observability-cassandra"
      containers: []
      tolerations:
      - key: "taint_for_obs_cass"
        operator: "Exists"
        effect: "NoExecute"
  resources:
    # we are using n2-standard-2 with taints so request most of resources
    requests:
      cpu: 1500m
      memory: 4Gi
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: cassandra
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  config:
    cassandra-yaml:
      num_tokens: 8
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 3G
      max_heap_size: 3G
      additional-jvm-opts:
      - -Dcassandra.system_distributed_replication_dc_names=jaeger
      - -Dcassandra.system_distributed_replication_per_dc=3
```

Here it is. It's basically the one from https://github.com/datastax/cass-operator/tree/master/docs/user with a couple tweaks. I've never run cass before, so I was trying to use sane defaults.
