### ISSUE TITLE
Per cassandra pod configuration

### ISSUE THREAD

**Issue by JeremiahDJordan** [datastax/cass-operator#396]
One thing that is not supported right now is having configuration options that are specific to a given pod.  This means you can not do things like make a new cluster that uses the exact same token layout as another cluster.  Not being able to do that means backing up and restoring to a new cluster is more time consuming, you can't just re-use existing data directories.

I would expect the configuration for this to look something like:

```
perPodConfigs:
  - rack: r1
    idx: 0
    config:
      tokens: [1, 100]
  - rack: r1
    idx: 1
    config:
      tokens: [50, 150]
    ...
```
