### ISSUE TITLE
README instructions don't work (namespacing issues)

### ISSUE THREAD

**Issue by Miles-Garnsey** [datastax/cass-operator#410]
It appears that the README instructions need to be updated. Currently, they suggest you install the operator using [these](https://raw.githubusercontent.com/datastax/cass-operator/v1.6.0/docs/user/cass-operator-manifests-v1.16.yaml) manifests, which namespaces it to `cass-operator`. The operator then listens only for resources created in that namespace.

The README then suggests you create the below `CassandraDatacenter` (which will be placed in the `default` namespace), and which will not work, because the operator is not listening to the `default` namespace.

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
```
