### ISSUE TITLE
Injection of volumeMount and environment variables to "cassandra" container

### ISSUE THREAD

**Issue by skhatri** [datastax/cass-operator#411]
Today, if we provide a container "cassandra" in our datacenter yaml, we get a duplicate container name error.

What are your thoughts on performing a merge (cherry-pick  for instance env, volumeMounts) so that we can easily inject environment variable and volume mounts. 

For example, "USE_MGMT_API" is hardcoded to true. It would be nice to be able to override that. Similarly, there are many env variables which could be overridden for cassandra and other modes.

**Comment by skhatri** [comment]
Update: 
We are still using 1.4.1 because of some metrics issue in 1.6.x. 
I updated to latest operator 1.6.0-ubi and the following podtemplatespec is merged as expected.

```
  podTemplateSpec:
    spec:
      containers: 
        - name: cassandra
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          env:
            - name: USE_MGMT_API
              value: "true"
            - name: ENVIRONMENT_NAME
              value: test
```

thank you.
