### ISSUE TITLE
pod goes to CrashLoopBackOff state (switching to "cassandra": operation not permitted) while creating CassandraDatacenter with non root user

### ISSUE THREAD

**Issue by dasuresh** [datastax/cass-operator#415]
oc version:
Client Version: 4.6.0-202101301510.p0-18d7461
Server Version: 4.6.16
Kubernetes Version: v1.19.0+e49167a

I am running entire steps with non-root user with admin access
cass-operator is up and running:
```
NAME                             READY   STATUS    RESTARTS   AGE
cass-operator-5996fbb889-59ftb   1/1     Running   0          17h

```
when i try to create CassandraDatacenter, its pods goes into CrashLoopBackOff state

```
kubectl logs -f cluster1-dc1-default-sts-0 cassandra
Starting Management API
Running java -Xms128m -Xmx128m -jar /opt/mgmtapi/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar --cassandra-socket /tmp/cassandra.sock --host tcp://0.0.0.0:8080 --host file:///tmp/oss-mgmt.sock --explicit-start true --cassandra-home /var/lib/cassandra/
error: failed switching to "cassandra": operation not permitted
```

I am using `example-cassdc-minimal.yaml` and only change done is storageClassName to rook-cephfs
below is the file
cat example-cassdc-minimal.yaml
```
# Sized to work on 3 k8s workers nodes with 1 core / 4 GB RAM
# See neighboring example-cassdc-full.yaml for docs for each parameter
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: rook-cephfs
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=3"
```
