### ISSUE TITLE
CassandraDatacenterStatus.LastRollingRestart is confusing

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#45]
I provisioned a cluster and was watching the status updates for the `CassandraDatacenter`.

On the first update the status looked like this:

```yaml
status:
  cassandraOperatorProgress: Updating
  lastRollingRestart: "2020-04-15T19:00:55Z"
  nodeStatuses: {}
```

`lastRollingRestart` never changes.  I see that it `LastRollingRestart` gets set and the status patched when the `CreateReconciliationContext` function in `context.go` is called.

I see that `LastRollingRestart` does get updated when a rolling restart is explicitly requested.

I found this a bit confusing initially as I was trying interpret and understand the status updates. Why does the status get updated with `LastRollingRestart` in the `CreateReconciliationContext` function?
