### ISSUE TITLE
Default super user not completely disabled in new cluster

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#71]
I am using v1.1.0 of the operator. Here is my cassdc spec:

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: multi-rack
spec:
  clusterName: multi-rack
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  size: 9
  racks:
  - name: us-east1-b
    zone: us-east1-b
  - name: us-east1-c
    zone: us-east1-c
  - name: us-east1-d
    zone: us-east1-d
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```
A quick test:
```
$ kubectl -n cass-operator exec -it multi-rack-multi-rack-us-east1-b-sts-0 -c cassandra -- cqlsh -u cassandra -p cassandra -e "select host_id from system.local"

 host_id
--------------------------------------
 f4164706-863f-45a9-9f6c-52860f61057f
```

And then another test to see what is in `system_auth.roles`:

```
$ kubectl -n cass-operator exec -it multi-rack-multi-rack-us-east1-b-sts-0 -c cassandra -- cqlsh -u cassandra -p cassandra -e "select * from system_auth.roles"

 role                 | can_login | is_superuser | member_of | salted_hash
----------------------+-----------+--------------+-----------+--------------------------------------------------------------
 multi-rack-superuser |      True |         True |      null | $2a$10$RcQf5.S1cQrOhI/8Jee8ZetGB434HB2tUE31d9glyPC4XX3q3f4PK
            cassandra |     False |        False |      null |
```

`can_login` and `is_superuser` are `False` for the `cassandra` user which is good, but there are a couple things that are bad IMO:

* The `cassandra` still exists at all
* The `cassandra` user is able to query `system_auth` tables which contain sensitive info

I assumed the following settings in `cassandra.yaml`:

```yaml
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer
```
I was surprised though to find

```yaml
authenticator: AllowAuthenticator
authorizer: AllowAuthorizer
```

This surprised me because in a stock Cassandra 3.11.x you cannot create a super user when auth is not enabled. I did a quick test with a 3.11.6 cluster that I created with ccm:

```
$ ccm node1 cqlsh -- -u cassandra -p cassandra -e "CREATE ROLE admin WITH SUPERUSER = true AND PASSWORD = 'admin'"
<stdin>:1:Unauthorized: Error from server: code=2100 [Unauthorized] message="Only superusers can create a role with superuser status"
```
My expectations are as follows:

* The `cassandra` user cannot log in or
* The `cassandra` user is removed (preferred)
* And authentication and authorization are enabled by default
