### ISSUE TITLE
CassandraDatacenter status updates not happening correctly during cluster creation

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#72]
I have reproduced this behavior consistently 3 or 4 times on a GKE cluster with 9 nodes spread across 3 zones. I am using v1.1.0 of the operator. Here is my cassdc spec:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: multi-rack
spec:
  clusterName: multi-rack
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  size: 9
  racks:
  - name: us-east1-b
    zone: us-east1-b
  - name: us-east1-c
    zone: us-east1-c
  - name: us-east1-d
    zone: us-east1-d
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

I was watching status updates in the console and I have seen multiple times now. I will show the last few status updates to give a better picture of what is happening.

With this first update, we see that 8 pods are reported:

```yaml
status:
  cassandraOperatorProgress: Updating
  lastRollingRestart: "2020-05-01T21:24:53Z"
  lastServerNodeStarted: "2020-05-01T21:33:08Z"
  nodeStatuses:
    multi-rack-multi-rack-us-east1-b-sts-0:
      hostID: 42a10825-ffca-43e0-8a44-13440fc0a586
      nodeIP: 10.28.8.4
    multi-rack-multi-rack-us-east1-b-sts-1:
      hostID: 6e496a9b-8a8a-43f7-9149-83ae15633cc1
      nodeIP: 10.28.3.3
    multi-rack-multi-rack-us-east1-b-sts-2:
      hostID: f3008646-ea00-4d74-9575-c90647a0811e
      nodeIP: 10.28.5.4
    multi-rack-multi-rack-us-east1-c-sts-0:
      hostID: d664763f-0e4c-4511-a720-14a494742de7
      nodeIP: 10.28.6.4
    multi-rack-multi-rack-us-east1-c-sts-2:
      hostID: f73691e4-b0b3-47fb-89c2-e7e6ecc62901
      nodeIP: 10.28.4.10
    multi-rack-multi-rack-us-east1-d-sts-0:
      hostID: 3cab2810-be05-497a-b22d-a98f286e181b
      nodeIP: 10.28.1.4
    multi-rack-multi-rack-us-east1-d-sts-1:
      hostID: 99ec2fc9-d40f-4c54-96f7-ccce3027aa66
      nodeIP: 10.28.2.3
    multi-rack-multi-rack-us-east1-d-sts-2:
      hostID: 9c35e2cd-4fb7-4365-a798-ea76f19bc96d
      nodeIP: 10.28.0.4
```

In the next update we see the `superUserUpsertedProperty` is set to indicate creation of the super user:

```yaml
status:
  cassandraOperatorProgress: Updating
  lastRollingRestart: "2020-05-01T21:24:53Z"
  lastServerNodeStarted: "2020-05-01T21:33:08Z"
  nodeStatuses:
    multi-rack-multi-rack-us-east1-b-sts-0:
      hostID: 42a10825-ffca-43e0-8a44-13440fc0a586
      nodeIP: 10.28.8.4
    multi-rack-multi-rack-us-east1-b-sts-1:
      hostID: 6e496a9b-8a8a-43f7-9149-83ae15633cc1
      nodeIP: 10.28.3.3
    multi-rack-multi-rack-us-east1-b-sts-2:
      hostID: f3008646-ea00-4d74-9575-c90647a0811e
      nodeIP: 10.28.5.4
    multi-rack-multi-rack-us-east1-c-sts-0:
      hostID: d664763f-0e4c-4511-a720-14a494742de7
      nodeIP: 10.28.6.4
    multi-rack-multi-rack-us-east1-c-sts-2:
      hostID: f73691e4-b0b3-47fb-89c2-e7e6ecc62901
      nodeIP: 10.28.4.10
    multi-rack-multi-rack-us-east1-d-sts-0:
      hostID: 3cab2810-be05-497a-b22d-a98f286e181b
      nodeIP: 10.28.1.4
    multi-rack-multi-rack-us-east1-d-sts-1:
      hostID: 99ec2fc9-d40f-4c54-96f7-ccce3027aa66
      nodeIP: 10.28.2.3
    multi-rack-multi-rack-us-east1-d-sts-2:
      hostID: 9c35e2cd-4fb7-4365-a798-ea76f19bc96d
      nodeIP: 10.28.0.4
  superUserUpserted: "2020-05-01T21:34:07Z"
```

Notice though that there are still only 8 pods in `nodeStatuses`.  `multi-rack-multi-rack-us-east1-c-sts-1` is missing.

In the next status update, we get `cassandraOperatorProgress: Ready` but `multi-rack-multi-rack-us-east1-c-sts-1` is still missing.

```yaml
status:
  cassandraOperatorProgress: Ready
  lastRollingRestart: "2020-05-01T21:24:53Z"
  lastServerNodeStarted: "2020-05-01T21:33:08Z"
  nodeStatuses:
    multi-rack-multi-rack-us-east1-b-sts-0:
      hostID: 42a10825-ffca-43e0-8a44-13440fc0a586
      nodeIP: 10.28.8.4
    multi-rack-multi-rack-us-east1-b-sts-1:
      hostID: 6e496a9b-8a8a-43f7-9149-83ae15633cc1
      nodeIP: 10.28.3.3
    multi-rack-multi-rack-us-east1-b-sts-2:
      hostID: f3008646-ea00-4d74-9575-c90647a0811e
      nodeIP: 10.28.5.4
    multi-rack-multi-rack-us-east1-c-sts-0:
      hostID: d664763f-0e4c-4511-a720-14a494742de7
      nodeIP: 10.28.6.4
    multi-rack-multi-rack-us-east1-c-sts-2:
      hostID: f73691e4-b0b3-47fb-89c2-e7e6ecc62901
      nodeIP: 10.28.4.10
    multi-rack-multi-rack-us-east1-d-sts-0:
      hostID: 3cab2810-be05-497a-b22d-a98f286e181b
      nodeIP: 10.28.1.4
    multi-rack-multi-rack-us-east1-d-sts-1:
      hostID: 99ec2fc9-d40f-4c54-96f7-ccce3027aa66
      nodeIP: 10.28.2.3
    multi-rack-multi-rack-us-east1-d-sts-2:
      hostID: 9c35e2cd-4fb7-4365-a798-ea76f19bc96d
      nodeIP: 10.28.0.4
  superUserUpserted: "2020-05-01T21:34:07Z"
```
Finally, we get:

```yaml
status:
  cassandraOperatorProgress: Ready
  lastRollingRestart: "2020-05-01T21:24:53Z"
  lastServerNodeStarted: "2020-05-01T21:33:08Z"
  nodeStatuses:
    multi-rack-multi-rack-us-east1-b-sts-0:
      hostID: 42a10825-ffca-43e0-8a44-13440fc0a586
      nodeIP: 10.28.8.4
    multi-rack-multi-rack-us-east1-b-sts-1:
      hostID: 6e496a9b-8a8a-43f7-9149-83ae15633cc1
      nodeIP: 10.28.3.3
    multi-rack-multi-rack-us-east1-b-sts-2:
      hostID: f3008646-ea00-4d74-9575-c90647a0811e
      nodeIP: 10.28.5.4
    multi-rack-multi-rack-us-east1-c-sts-0:
      hostID: d664763f-0e4c-4511-a720-14a494742de7
      nodeIP: 10.28.6.4
    multi-rack-multi-rack-us-east1-c-sts-1:
      hostID: 6bc7b1d7-53fa-4196-8629-bf9fdfae8a25
      nodeIP: 10.28.7.4
    multi-rack-multi-rack-us-east1-c-sts-2:
      hostID: f73691e4-b0b3-47fb-89c2-e7e6ecc62901
      nodeIP: 10.28.4.10
    multi-rack-multi-rack-us-east1-d-sts-0:
      hostID: 3cab2810-be05-497a-b22d-a98f286e181b
      nodeIP: 10.28.1.4
    multi-rack-multi-rack-us-east1-d-sts-1:
      hostID: 99ec2fc9-d40f-4c54-96f7-ccce3027aa66
      nodeIP: 10.28.2.3
    multi-rack-multi-rack-us-east1-d-sts-2:
      hostID: 9c35e2cd-4fb7-4365-a798-ea76f19bc96d
      nodeIP: 10.28.0.4
  superUserUpserted: "2020-05-01T21:34:07Z"
```
I can provide the full operator log if that is useful.
